// GENERATED CODE - DO NOT MODIFY BY HAND
// Regenerate with: dart run tool/gen_tools_search_index.dart
//
// Source of truth is the settings screens themselves; this file
// mirrors every row an author marked searchable so search can
// never silently miss one. See tool/tools_search_index.dart.

import 'package:reclash/l10n/l10n.dart';

/// One searchable setting harvested from a tool screen: the row
/// title, the pane it lives in, its category, the availability gate
/// token, and any extra search keywords.
class DeepSettingSpec {
  const DeepSettingSpec({
    required this.title,
    required this.paneId,
    required this.category,
    required this.gate,
    this.keywords = const [],
  });

  final String title;
  final String paneId;
  final String category;
  final String gate;
  final List<String> keywords;
}

/// Every searchable setting row across the tool screens,
/// resolved against the active locale, in source order per
/// owner.
List<DeepSettingSpec> deepSettingSpecs(AppLocalizations l) {
  return [
    DeepSettingSpec(
      title: l.network,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'DNS',
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'NTP',
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.addedRules,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.script,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartPause,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRouting,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.desync,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.extra,
      paneId: 'advanced',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.userAgent,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.keepAliveIntervalDesc,
      paneId: 'config',
      category: 'configuration',
      gate: 'desktop',
    ),
    DeepSettingSpec(
      title: l.testUrl,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.port,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'Hosts',
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.authentication,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.account,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.password,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.sendDeviceIdentity,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.appRegion,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.network,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.allowLan,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.identity,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.other,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.appendSystemDns,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'IPv6',
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.unifiedDelay,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.tcpConcurrent,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.findProcessMode,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.geodataLoader,
      paneId: 'config',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.logLevel,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.notification,
      paneId: 'application',
      category: 'application',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.minimizeOnExit,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.autoLaunch,
      paneId: 'application',
      category: 'application',
      gate: 'desktop',
    ),
    DeepSettingSpec(
      title: l.silentLaunch,
      paneId: 'application',
      category: 'application',
      gate: 'desktop',
    ),
    DeepSettingSpec(
      title: l.highPriorityAutoLaunch,
      paneId: 'application',
      category: 'application',
      gate: 'windows',
    ),
    DeepSettingSpec(
      title: l.autoRun,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.exclude,
      paneId: 'application',
      category: 'application',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.autoCloseConnections,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.onlyStatisticsProxy,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.autoCheckUpdate,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.checkCertificate,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.logcat,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.crashlytics,
      paneId: 'application',
      category: 'application',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.other,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.logsAndDiagnostics,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.settings,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.setupRerun,
      paneId: 'application',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.schedule,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.darkAt,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.lightAt,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.contrast,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.dashboardStyle,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.themeMode,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.pureBlackMode,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.textScale,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.tabAnimation,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.animations,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.reduceMotion,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.predictiveBack,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.appearance,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.seasonalDecorations,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.providerEffects,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.milestoneDecorations,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperTitle,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperEnabled,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperProviderPriority,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperLayout,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperFit,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperEffects,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperReadability,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.wallpaperReset,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.themeColor,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.findingPorcelain,
      paneId: 'appearance',
      category: 'application',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.appearanceIcon,
      paneId: 'appearance',
      category: 'application',
      gate: 'android',
    ),
    const DeepSettingSpec(
      title: 'VPN',
      paneId: 'network',
      category: 'configuration',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.tun,
      paneId: 'network',
      category: 'configuration',
      gate: 'desktop',
    ),
    DeepSettingSpec(
      title: l.allowBypass,
      paneId: 'network',
      category: 'configuration',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.systemProxy,
      paneId: 'network',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'IPv6',
      paneId: 'network',
      category: 'configuration',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.autoSetSystemDns,
      paneId: 'network',
      category: 'configuration',
      gate: 'macos',
    ),
    DeepSettingSpec(
      title: l.dnsHijacking,
      paneId: 'network',
      category: 'configuration',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.stackMode,
      paneId: 'network',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.interfaceNameMode,
      paneId: 'network',
      category: 'configuration',
      gate: 'desktop',
    ),
    DeepSettingSpec(
      title: l.interfaceName,
      paneId: 'network',
      category: 'configuration',
      gate: 'desktop',
    ),
    DeepSettingSpec(
      title: l.routeMode,
      paneId: 'network',
      category: 'configuration',
      gate: 'mobile',
    ),
    DeepSettingSpec(
      title: l.overrideNetworkSettings,
      paneId: 'network',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.bypassDomain,
      paneId: 'network',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.routeAddress,
      paneId: 'network',
      category: 'configuration',
      gate: 'mobile',
    ),
    DeepSettingSpec(
      title: l.options,
      paneId: 'network',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.status,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.listen,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.useHosts,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.useSystemHosts,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'IPv6',
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.respectRules,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'PreferH3',
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.dnsMode,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.fakeipRange,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.fakeipFilter,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.defaultNameserver,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.nameserverPolicy,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.nameserver,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.fallback,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.proxyNameserver,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'Geoip',
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.geoipCode,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    const DeepSettingSpec(
      title: 'Geosite',
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.ipcidr,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.domain,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.overrideDns,
      paneId: 'dns',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.status,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.server,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.port,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.interval,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.dialerProxy,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.writeToSystem,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.overrideNtp,
      paneId: 'ntp',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingStrategy,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingKeyAdmission,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingDomestic,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingRequireUdp,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceRoutes,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingBehaviour,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingManualHold,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingDiagnostics,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingBackup,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingExport,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingImport,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingPacing,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingDwell,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingWave,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCeiling,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingDegradeConfirm,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingProofTtl,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingRanking,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingLatencyBands,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingSignals,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingProbes,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCanariesForeign,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCanariesDomestic,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCensorSni,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingMarkers,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingMarkersOpen,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingMarkersDomestic,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingMarkersLocal,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCountryPolicy,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCensor,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingAvoidCountries,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingEgress,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingEgressEchoes,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingCountryEchoes,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingHeuristics,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingNameHints,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingBreakerPatterns,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingTriggers,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingSwitchImproveMs,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingSwitchImprovePct,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingLatencyStep,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingRules,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceStatus,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceRoute,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceEnabled,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceFallback,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceSources,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceProviderSource,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceManual,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartRoutingServiceManualEmpty,
      paneId: 'smartRouting',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.ignoreBatteryOptimization,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'android',
    ),
    DeepSettingSpec(
      title: l.locationPermission,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartPause,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartPauseCloseConnections,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartPauseStrict,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.smartPauseFullStop,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.trustedNetworks,
      paneId: 'smartPause',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.desyncFeatureEnable,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncStrategySection,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncArgs,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncDefaultName,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncEngine,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.port,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncCache,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncCacheTtl,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncRouting,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncForceTcp,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncRoutingRules,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.desyncRoutingNoCategories,
      paneId: 'desync',
      category: 'configuration',
      gate: 'byeDpi',
    ),
    DeepSettingSpec(
      title: l.noInfo,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.file,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.backup,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.restore,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.local,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.options,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.dangerZone,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.clearData,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.restoreStrategy,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.restoreOnlyConfig,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.restoreAllData,
      paneId: 'backup',
      category: 'configuration',
      gate: 'always',
    ),
    DeepSettingSpec(
      title: l.developerSubscriptions,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.options,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.messageTest,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.logsTest,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.crashTest,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.clearData,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.pruneCache,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.developerMode,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
    DeepSettingSpec(
      title: l.developerFindings,
      paneId: 'developer',
      category: 'info',
      gate: 'developerMode',
    ),
  ];
}
