import 'dart:async';
import 'dart:io';

import 'package:reclash/common/boot_guard.dart';
import 'package:reclash/common/common.dart';
import 'package:reclash/common/system_dns.dart';
import 'package:reclash/core/core.dart';
import 'package:reclash/database/database.dart';
import 'package:reclash/enum/enum.dart';
import 'package:reclash/models/models.dart';
import 'package:reclash/plugins/app.dart';
import 'package:reclash/plugins/service.dart';
import 'package:reclash/providers/actions/system_exit.dart';
import 'package:reclash/providers/providers.dart';
import 'package:reclash/state.dart';
import 'package:reclash/widgets/dialog.dart';
import 'package:device_info_plus/device_info_plus.dart';
import 'package:dio/dio.dart' show CancelToken;
import 'package:material_ui/material_ui.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path/path.dart' show basename, join;
import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:url_launcher/url_launcher.dart';

part 'actions/common.dart';
part 'actions/setup.dart';
part 'actions/backup.dart';
part 'actions/core.dart';
part 'actions/system.dart';
part 'actions/store.dart';
part 'actions/theme.dart';
part 'actions/proxies.dart';
part 'actions/profiles.dart';
part 'actions/geo_resource.dart';
part 'actions/updating.dart';
part 'actions/app_update.dart';
part 'generated/action.g.dart';
