//go:build linux

package main

import (
	"strings"
	"testing"
)

const rcxRouteFixture = `Iface	Destination	Gateway 	Flags	RefCnt	Use	Metric	Mask		MTU	Window	IRTT
ReClash	00000000	00000000	0001	0	0	0	00000000	0	0	0
wlp7s0	00000000	011FA8C0	0003	0	0	20600	00000000	0	0	0
wlp7s0	5817D75D	011FA8C0	0007	0	0	100	FFFFFFFF	0	0	0
docker0	000011AC	00000000	0001	0	0	0	0000FFFF	0	0	0
eth0	00000000	0101A8C0	0003	0	0	100	00000000	0	0	0
`

func TestRouteTableYieldsOnlyTheNamedLinksDefaults(t *testing.T) {
	gateways := rcxParseRoutes(rcxRouteFixture, []string{"wlp7s0", "eth0"})

	if got := strings.Join(gateways, ","); got != "192.168.1.1,192.168.31.1" {
		t.Errorf("gateways = %q, want both physical defaults in a stable order", got)
	}
}

func TestRouteTableLeavesOutLinksItWasNotAsked(t *testing.T) {
	gateways := rcxParseRoutes(rcxRouteFixture, []string{"wlp7s0"})

	if got := strings.Join(gateways, ","); got != "192.168.31.1" {
		t.Errorf("gateways = %q, want the tunnel and the bridges left out", got)
	}
}

func TestRouteTableIgnoresRoutesThatAreNotDefaults(t *testing.T) {
	if got := rcxParseRoutes(rcxRouteFixture, []string{"docker0"}); len(got) != 0 {
		t.Errorf("gateways = %v, want none: a subnet route is not a link's gateway", got)
	}
}

// A point-to-point default prints a zero gateway, the same one on every network.
func TestRouteTableIgnoresAnOnLinkDefault(t *testing.T) {
	if got := rcxParseRoutes(rcxRouteFixture, []string{"ReClash"}); len(got) != 0 {
		t.Errorf("gateways = %v, want none for a default without a gateway", got)
	}
}

func TestResolversComeBackSortedAndParsed(t *testing.T) {
	conf := "# Generated by NetworkManager\nnameserver 192.168.31.1\noptions edns0\n" +
		"#nameserver 8.8.8.8\nnameserver 1.1.1.1\nnameserver nonsense\n"

	if got := strings.Join(rcxParseResolvers(conf), ","); got != "1.1.1.1,192.168.31.1" {
		t.Errorf("resolvers = %q, want the addresses only, in a stable order", got)
	}
}
