// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/editor.dart';
import 'api/ipc.dart';
import 'api/script.dart';
import 'api/windows.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiInitInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -2080320147;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_api',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  List<String> crateApiEditorRopeBridgeCachedLinesRange({
    required RopeBridge that,
    required BigInt startLine,
    required BigInt endLine,
  });

  BigInt crateApiEditorRopeBridgeCharToLine({
    required RopeBridge that,
    required BigInt charIdx,
  });

  RopeBridge crateApiEditorRopeBridgeCreate({required String initialText});

  String crateApiEditorRopeBridgeGetText({required RopeBridge that});

  void crateApiEditorRopeBridgeInsert({
    required RopeBridge that,
    required BigInt charIdx,
    required String text,
  });

  BigInt crateApiEditorRopeBridgeLenChars({required RopeBridge that});

  BigInt crateApiEditorRopeBridgeLenLines({required RopeBridge that});

  String crateApiEditorRopeBridgeLine({
    required RopeBridge that,
    required BigInt lineIdx,
  });

  BigInt crateApiEditorRopeBridgeLineToChar({
    required RopeBridge that,
    required BigInt lineIdx,
  });

  void crateApiEditorRopeBridgeRemove({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  });

  String crateApiEditorRopeBridgeSlice({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  });

  bool crateApiWindowsCancelWindowsCoreLaunch({required String sessionId});

  Future<String> crateApiScriptEvaluateScript({
    required String script,
    required String config,
  });

  Future<List<RustFoldRange>> crateApiEditorFoldsComputeAll({
    required RopeBridge rope,
    required BigInt tabSize,
  });

  BigInt? crateApiEditorFoldsFindMatchingBracket({
    required RopeBridge rope,
    required BigInt targetOffset,
  });

  List<GuideBlock> crateApiEditorGuidesComputeViewport({
    required RopeBridge rope,
    required BigInt firstVisible,
    required BigInt lastVisible,
    required BigInt tabSize,
  });

  Future<void> crateApiInitInitApp();

  Stream<List<String>> crateApiWindowsLaunchWindowsCore({
    required String sessionId,
    required String address,
    required String homeDir,
    required String expectedSha256,
  });

  void crateApiWindowsPrepareWindowsCoreLaunch({required String sessionId});

  Stream<Uint8List> crateApiIpcRestartIpcServer({required String name});

  Future<void> crateApiIpcSendIpcMessage({required List<int> data});

  Future<void> crateApiIpcStopIpcServer();

  Future<bool> crateApiWindowsStopWindowsCore({
    required String sessionId,
    required int timeoutMillis,
  });

  Future<bool> crateApiWindowsWindowsIsElevated();

  Future<List<String>> crateApiEditorWordsExtract({required RopeBridge rope});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RopeBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RopeBridge;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_RopeBridgePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  List<String> crateApiEditorRopeBridgeCachedLinesRange({
    required RopeBridge that,
    required BigInt startLine,
    required BigInt endLine,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(startLine, serializer);
          sse_encode_usize(endLine, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeCachedLinesRangeConstMeta,
        argValues: [that, startLine, endLine],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeCachedLinesRangeConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_cached_lines_range",
        argNames: ["that", "startLine", "endLine"],
      );

  @override
  BigInt crateApiEditorRopeBridgeCharToLine({
    required RopeBridge that,
    required BigInt charIdx,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(charIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeCharToLineConstMeta,
        argValues: [that, charIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeCharToLineConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_char_to_line",
        argNames: ["that", "charIdx"],
      );

  @override
  RopeBridge crateApiEditorRopeBridgeCreate({required String initialText}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(initialText, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeCreateConstMeta,
        argValues: [initialText],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeCreateConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_create",
        argNames: ["initialText"],
      );

  @override
  String crateApiEditorRopeBridgeGetText({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeGetTextConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeGetTextConstMeta =>
      const TaskConstMeta(debugName: "RopeBridge_get_text", argNames: ["that"]);

  @override
  void crateApiEditorRopeBridgeInsert({
    required RopeBridge that,
    required BigInt charIdx,
    required String text,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(charIdx, serializer);
          sse_encode_String(text, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeInsertConstMeta,
        argValues: [that, charIdx, text],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeInsertConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_insert",
        argNames: ["that", "charIdx", "text"],
      );

  @override
  BigInt crateApiEditorRopeBridgeLenChars({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeLenCharsConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeLenCharsConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_len_chars",
        argNames: ["that"],
      );

  @override
  BigInt crateApiEditorRopeBridgeLenLines({required RopeBridge that}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeLenLinesConstMeta,
        argValues: [that],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeLenLinesConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_len_lines",
        argNames: ["that"],
      );

  @override
  String crateApiEditorRopeBridgeLine({
    required RopeBridge that,
    required BigInt lineIdx,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(lineIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeLineConstMeta,
        argValues: [that, lineIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeLineConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_line",
        argNames: ["that", "lineIdx"],
      );

  @override
  BigInt crateApiEditorRopeBridgeLineToChar({
    required RopeBridge that,
    required BigInt lineIdx,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(lineIdx, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeLineToCharConstMeta,
        argValues: [that, lineIdx],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeLineToCharConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_line_to_char",
        argNames: ["that", "lineIdx"],
      );

  @override
  void crateApiEditorRopeBridgeRemove({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(start, serializer);
          sse_encode_usize(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeRemoveConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeRemoveConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_remove",
        argNames: ["that", "start", "end"],
      );

  @override
  String crateApiEditorRopeBridgeSlice({
    required RopeBridge that,
    required BigInt start,
    required BigInt end,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            that,
            serializer,
          );
          sse_encode_usize(start, serializer);
          sse_encode_usize(end, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorRopeBridgeSliceConstMeta,
        argValues: [that, start, end],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorRopeBridgeSliceConstMeta =>
      const TaskConstMeta(
        debugName: "RopeBridge_slice",
        argNames: ["that", "start", "end"],
      );

  @override
  bool crateApiWindowsCancelWindowsCoreLaunch({required String sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWindowsCancelWindowsCoreLaunchConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowsCancelWindowsCoreLaunchConstMeta =>
      const TaskConstMeta(
        debugName: "cancel_windows_core_launch",
        argNames: ["sessionId"],
      );

  @override
  Future<String> crateApiScriptEvaluateScript({
    required String script,
    required String config,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(script, serializer);
          sse_encode_String(config, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiScriptEvaluateScriptConstMeta,
        argValues: [script, config],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiScriptEvaluateScriptConstMeta =>
      const TaskConstMeta(
        debugName: "evaluate_script",
        argNames: ["script", "config"],
      );

  @override
  Future<List<RustFoldRange>> crateApiEditorFoldsComputeAll({
    required RopeBridge rope,
    required BigInt tabSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          sse_encode_usize(tabSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_rust_fold_range,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorFoldsComputeAllConstMeta,
        argValues: [rope, tabSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorFoldsComputeAllConstMeta =>
      const TaskConstMeta(
        debugName: "folds_compute_all",
        argNames: ["rope", "tabSize"],
      );

  @override
  BigInt? crateApiEditorFoldsFindMatchingBracket({
    required RopeBridge rope,
    required BigInt targetOffset,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          sse_encode_usize(targetOffset, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_usize,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorFoldsFindMatchingBracketConstMeta,
        argValues: [rope, targetOffset],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorFoldsFindMatchingBracketConstMeta =>
      const TaskConstMeta(
        debugName: "folds_find_matching_bracket",
        argNames: ["rope", "targetOffset"],
      );

  @override
  List<GuideBlock> crateApiEditorGuidesComputeViewport({
    required RopeBridge rope,
    required BigInt firstVisible,
    required BigInt lastVisible,
    required BigInt tabSize,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          sse_encode_usize(firstVisible, serializer);
          sse_encode_usize(lastVisible, serializer);
          sse_encode_usize(tabSize, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_guide_block,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorGuidesComputeViewportConstMeta,
        argValues: [rope, firstVisible, lastVisible, tabSize],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorGuidesComputeViewportConstMeta =>
      const TaskConstMeta(
        debugName: "guides_compute_viewport",
        argNames: ["rope", "firstVisible", "lastVisible", "tabSize"],
      );

  @override
  Future<void> crateApiInitInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Stream<List<String>> crateApiWindowsLaunchWindowsCore({
    required String sessionId,
    required String address,
    required String homeDir,
    required String expectedSha256,
  }) {
    final sink = RustStreamSink<List<String>>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(sessionId, serializer);
            sse_encode_String(address, serializer);
            sse_encode_String(homeDir, serializer);
            sse_encode_String(expectedSha256, serializer);
            sse_encode_StreamSink_list_String_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 18,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiWindowsLaunchWindowsCoreConstMeta,
          argValues: [sessionId, address, homeDir, expectedSha256, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWindowsLaunchWindowsCoreConstMeta =>
      const TaskConstMeta(
        debugName: "launch_windows_core",
        argNames: ["sessionId", "address", "homeDir", "expectedSha256", "sink"],
      );

  @override
  void crateApiWindowsPrepareWindowsCoreLaunch({required String sessionId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWindowsPrepareWindowsCoreLaunchConstMeta,
        argValues: [sessionId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowsPrepareWindowsCoreLaunchConstMeta =>
      const TaskConstMeta(
        debugName: "prepare_windows_core_launch",
        argNames: ["sessionId"],
      );

  @override
  Stream<Uint8List> crateApiIpcRestartIpcServer({required String name}) {
    final sink = RustStreamSink<Uint8List>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(name, serializer);
            sse_encode_StreamSink_list_prim_u_8_strict_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 20,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_String,
          ),
          constMeta: kCrateApiIpcRestartIpcServerConstMeta,
          argValues: [name, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiIpcRestartIpcServerConstMeta =>
      const TaskConstMeta(
        debugName: "restart_ipc_server",
        argNames: ["name", "sink"],
      );

  @override
  Future<void> crateApiIpcSendIpcMessage({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIpcSendIpcMessageConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIpcSendIpcMessageConstMeta =>
      const TaskConstMeta(debugName: "send_ipc_message", argNames: ["data"]);

  @override
  Future<void> crateApiIpcStopIpcServer() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiIpcStopIpcServerConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiIpcStopIpcServerConstMeta =>
      const TaskConstMeta(debugName: "stop_ipc_server", argNames: []);

  @override
  Future<bool> crateApiWindowsStopWindowsCore({
    required String sessionId,
    required int timeoutMillis,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(sessionId, serializer);
          sse_encode_u_32(timeoutMillis, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWindowsStopWindowsCoreConstMeta,
        argValues: [sessionId, timeoutMillis],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowsStopWindowsCoreConstMeta =>
      const TaskConstMeta(
        debugName: "stop_windows_core",
        argNames: ["sessionId", "timeoutMillis"],
      );

  @override
  Future<bool> crateApiWindowsWindowsIsElevated() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWindowsWindowsIsElevatedConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWindowsWindowsIsElevatedConstMeta =>
      const TaskConstMeta(debugName: "windows_is_elevated", argNames: []);

  @override
  Future<List<String>> crateApiEditorWordsExtract({required RopeBridge rope}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
            rope,
            serializer,
          );
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEditorWordsExtractConstMeta,
        argValues: [rope],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEditorWordsExtractConstMeta =>
      const TaskConstMeta(debugName: "words_extract", argNames: ["rope"]);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_RopeBridge => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_RopeBridge => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RopeBridge
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RopeBridge
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RopeBridge
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<List<String>> dco_decode_StreamSink_list_String_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<Uint8List> dco_decode_StreamSink_list_prim_u_8_strict_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_usize(raw);
  }

  @protected
  GuideBlock dco_decode_guide_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GuideBlock(
      startLine: dco_decode_i_32(arr[0]),
      endLine: dco_decode_i_32(arr[1]),
      indentLevel: dco_decode_i_32(arr[2]),
      leadingSpaces: dco_decode_i_32(arr[3]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<GuideBlock> dco_decode_list_guide_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_guide_block).toList();
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RustFoldRange> dco_decode_list_rust_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_rust_fold_range).toList();
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_usize(raw);
  }

  @protected
  RustFoldRange dco_decode_rust_fold_range(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return RustFoldRange(
      startLine: dco_decode_i_32(arr[0]),
      endLine: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RopeBridge
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RopeBridge
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RopeBridge
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return RopeBridgeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  RustStreamSink<List<String>> sse_decode_StreamSink_list_String_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<Uint8List> sse_decode_StreamSink_list_prim_u_8_strict_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_usize(deserializer));
  }

  @protected
  GuideBlock sse_decode_guide_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startLine = sse_decode_i_32(deserializer);
    var var_endLine = sse_decode_i_32(deserializer);
    var var_indentLevel = sse_decode_i_32(deserializer);
    var var_leadingSpaces = sse_decode_i_32(deserializer);
    return GuideBlock(
      startLine: var_startLine,
      endLine: var_endLine,
      indentLevel: var_indentLevel,
      leadingSpaces: var_leadingSpaces,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<GuideBlock> sse_decode_list_guide_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <GuideBlock>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_guide_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RustFoldRange> sse_decode_list_rust_fold_range(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RustFoldRange>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_rust_fold_range(deserializer));
    }
    return ans_;
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_usize(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RustFoldRange sse_decode_rust_fold_range(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_startLine = sse_decode_i_32(deserializer);
    var var_endLine = sse_decode_i_32(deserializer);
    return RustFoldRange(startLine: var_startLine, endLine: var_endLine);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    RopeBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RopeBridgeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    RopeBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RopeBridgeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerRopeBridge(
    RopeBridge self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as RopeBridgeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_String_Sse(
    RustStreamSink<List<String>> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_list_prim_u_8_strict_Sse(
    RustStreamSink<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self, serializer);
  }

  @protected
  void sse_encode_guide_block(GuideBlock self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.startLine, serializer);
    sse_encode_i_32(self.endLine, serializer);
    sse_encode_i_32(self.indentLevel, serializer);
    sse_encode_i_32(self.leadingSpaces, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_guide_block(
    List<GuideBlock> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_guide_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_rust_fold_range(
    List<RustFoldRange> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_rust_fold_range(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_usize(
    BigInt? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_usize(self, serializer);
    }
  }

  @protected
  void sse_encode_rust_fold_range(
    RustFoldRange self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.startLine, serializer);
    sse_encode_i_32(self.endLine, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class RopeBridgeImpl extends RustOpaque implements RopeBridge {
  // Not to be used by end users
  RopeBridgeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  RopeBridgeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_RopeBridge,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_RopeBridge,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_RopeBridgePtr,
  );

  List<String> cachedLinesRange({
    required BigInt startLine,
    required BigInt endLine,
  }) => RustLib.instance.api.crateApiEditorRopeBridgeCachedLinesRange(
    that: this,
    startLine: startLine,
    endLine: endLine,
  );

  BigInt charToLine({required BigInt charIdx}) => RustLib.instance.api
      .crateApiEditorRopeBridgeCharToLine(that: this, charIdx: charIdx);

  String getText() =>
      RustLib.instance.api.crateApiEditorRopeBridgeGetText(that: this);

  void insert({required BigInt charIdx, required String text}) => RustLib
      .instance
      .api
      .crateApiEditorRopeBridgeInsert(that: this, charIdx: charIdx, text: text);

  BigInt lenChars() =>
      RustLib.instance.api.crateApiEditorRopeBridgeLenChars(that: this);

  BigInt lenLines() =>
      RustLib.instance.api.crateApiEditorRopeBridgeLenLines(that: this);

  String line({required BigInt lineIdx}) => RustLib.instance.api
      .crateApiEditorRopeBridgeLine(that: this, lineIdx: lineIdx);

  BigInt lineToChar({required BigInt lineIdx}) => RustLib.instance.api
      .crateApiEditorRopeBridgeLineToChar(that: this, lineIdx: lineIdx);

  void remove({required BigInt start, required BigInt end}) => RustLib
      .instance
      .api
      .crateApiEditorRopeBridgeRemove(that: this, start: start, end: end);

  String slice({required BigInt start, required BigInt end}) => RustLib
      .instance
      .api
      .crateApiEditorRopeBridgeSlice(that: this, start: start, end: end);
}
