import 'package:flutter_test/flutter_test.dart';
import 'package:reclash/common/incy_links.dart';
import 'package:reclash/enum/enum.dart';

// Generated by the reference implementation (@incy/link-encoder, MIT) with
// IV 00..0b over {"n":"Test provider","url":"https://duckvpn.tech/sub/…","v":1}.
const _crypt1Vector =
    'incy://crypt1/AAECAwQFBgcICQoLNyILfyzDr1Fxn34D88TTDqLf-oNELzHPSWrfIN3ASn0soKcNUVYYzdAANve-SW7JDPuJ-GGTPfEfbvjoEyKSsaSQ3JCaY_oxLvPAJlQ1Q3coiTWpUzouWimxoDCBYcDphGTtc6h4CtDKVWhFaTYiPvE';

const _vectorUrl =
    'https://duckvpn.tech/sub/3404b41d-2ed2-4754-95d4-3d7745ff5f2e';

void main() {
  group('resolveExternalLink', () {
    test('decrypts a crypt1 vector link', () async {
      final resolved = await resolveExternalLink(_crypt1Vector);
      expect(resolved, isNotNull);
      expect(resolved!.url, _vectorUrl);
      expect(resolved.name, 'Test provider');
      expect(resolved.preset, SubscriptionClient.incy);
      expect(resolved.data, isNull);
    });

    test('a tampered ciphertext fails authentication', () async {
      final tampered = _crypt1Vector.replaceRange(30, 31, 'X');
      await expectLater(
        resolveExternalLink(tampered),
        throwsA(isA<IncyLinkException>()),
      );
    });

    test('malformed payloads are rejected, not thrown as raw errors',
        () async {
      await expectLater(
        resolveExternalLink('incy://crypt1/'),
        throwsA(isA<IncyLinkException>()),
      );
      await expectLater(
        resolveExternalLink('incy://crypt1/AAAA'),
        throwsA(isA<IncyLinkException>()),
      );
      await expectLater(
        resolveExternalLink('incy://crypt2/whatever'),
        throwsA(isA<IncyLinkException>()),
      );
    });

    test('happ crypto links are rejected as out of scope', () async {
      await expectLater(
        resolveExternalLink('happ://crypt2/AAAA'),
        throwsA(isA<IncyLinkException>()),
      );
    });

    test('incy://add/ unwraps a percent-encoded url', () async {
      final resolved = await resolveExternalLink(
        'incy://add/https%3A%2F%2Fexample.com%2Fsub%3Ftoken%3D1',
      );
      expect(resolved, isNotNull);
      expect(resolved!.url, 'https://example.com/sub?token=1');
      expect(resolved.preset, SubscriptionClient.incy);
    });

    test('happ://add/ sets the happ preset', () async {
      final resolved = await resolveExternalLink(
        'happ://add/https%3A%2F%2Fexample.com%2Fsub',
      );
      expect(resolved, isNotNull);
      expect(resolved!.url, 'https://example.com/sub');
      expect(resolved.preset, SubscriptionClient.happ);
    });

    test('add wrappers may carry an encrypted link', () async {
      final resolved = await resolveExternalLink(
        'incy://add/${Uri.encodeComponent(_crypt1Vector)}',
      );
      expect(resolved, isNotNull);
      expect(resolved!.url, _vectorUrl);
      expect(resolved.name, 'Test provider');
    });

    test('incy://import/ with a raw payload yields data, not a url',
        () async {
      final payload = Uri.encodeComponent(
        'vless://uuid@host:443?security=tls#node1\nvless://uuid@host2:443#node2',
      );
      final resolved = await resolveExternalLink('incy://import/$payload');
      expect(resolved, isNotNull);
      expect(resolved!.url, isEmpty);
      expect(resolved.data, contains('vless://uuid@host:443'));
      expect(resolved.preset, SubscriptionClient.incy);
    });

    test('incy://import/ with a url payload resolves to the url', () async {
      final resolved = await resolveExternalLink(
        'incy://import/https%3A%2F%2Fexample.com%2Fsub',
      );
      expect(resolved, isNotNull);
      expect(resolved!.url, 'https://example.com/sub');
      expect(resolved.data, isNull);
    });

    test('an http url embedding a deep link unwraps it', () async {
      final resolved = await resolveExternalLink(
        'https://t.me/share/url?url=${Uri.encodeComponent(_crypt1Vector)}',
      );
      expect(resolved, isNotNull);
      expect(resolved!.url, _vectorUrl);
      expect(resolved.name, 'Test provider');
    });

    test('plain urls and garbage are not external links', () async {
      expect(await resolveExternalLink(''), isNull);
      expect(
        await resolveExternalLink('https://example.com/sub'),
        isNull,
      );
      expect(await resolveExternalLink('vless://u@h:1#n'), isNull);
    });
  });
}
