display_name: ReClash
package_name: reclash
maintainer:
  name: Hoxiee
  email: hoxiee.dev@gmail.com

priority: optional
section: x11
installed_size: 6604
essential: false
icon: ./assets/images/icon.png

dependencies:
  - libayatana-appindicator3-dev
  - libkeybinder-3.0-dev
  - libsecret-1-0

keywords:
  - ReClash
  - Clash
  - ClashMeta
  - Proxy

generic_name: ReClash

categories:
  - Network

startup_notify: true
