// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<bool> windowsIsElevated() =>
    RustLib.instance.api.crateApiWindowsWindowsIsElevated();

void prepareWindowsCoreLaunch({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiWindowsPrepareWindowsCoreLaunch(sessionId: sessionId);

Stream<List<String>> launchWindowsCore({
  required String sessionId,
  required String address,
  required String homeDir,
  required String expectedSha256,
}) => RustLib.instance.api.crateApiWindowsLaunchWindowsCore(
  sessionId: sessionId,
  address: address,
  homeDir: homeDir,
  expectedSha256: expectedSha256,
);

bool cancelWindowsCoreLaunch({required String sessionId}) => RustLib
    .instance
    .api
    .crateApiWindowsCancelWindowsCoreLaunch(sessionId: sessionId);

Future<bool> stopWindowsCore({
  required String sessionId,
  required int timeoutMillis,
}) => RustLib.instance.api.crateApiWindowsStopWindowsCore(
  sessionId: sessionId,
  timeoutMillis: timeoutMillis,
);
